---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/app: mysql
data:
  primary.cnf: |
    # primary only config
    [mysqld]
    log-bin

  replica.cnf: |
    # replica only
    [mysqld]
    super-read-only