name: build-base-image
run-name: Build base image
on:
  push:
    branches:
      - main
jobs:
  create-builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: base-image:latest
        outputs: type=docker,dest=/tmp/base-image.tar
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: base-image
        path: /tmp/base-image.tar
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build-users-service:
    runs-on: ubuntu-latest
    needs: create-builder
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: base-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/base-image.tar
          docker image ls -a
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: crates/users-service
          tags: users-service:latest