name: build-base-image
run-name: Build base image
on:
  push:
    branches:
      - main
jobs:
  create-builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: base-image:latest
        outputs: type=docker,dest=/tmp/base-image.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: base-image
        path: /tmp/base-image.tar
  build-users-service:
    runs-on: ubuntu-latest
    needs: build-base-image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: base-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/base-image.tar
          docker image ls -a
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: crates/users-service
          tags: users-service:latest