name: build-base-image
run-name: Build base image
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io


jobs:
  create-builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: base-image:latest
        outputs: type=docker,dest=/tmp/base-image.tar
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: base-image
        path: /tmp/base-image.tar
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build-users-service:
    runs-on: ubuntu-latest
    needs: create-builder
    env:
      IMAGE_NAME: users-service
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: base-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/base-image.tar
          docker image ls -a
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge,enable=true,prefix=,suffix=,branch=main
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: crates/users-service
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true