name: build-users-service-image
on:
  workflow_run:
    types:
      - completed
    workflows:
      - build-base-image
jobs:
  build_users_service:
    runs-on: ubuntu-latest
    needs: build-base-image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: base-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/base-image.tar
          docker image ls -a
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: crates/users-service
          tags: users-service:latest
